<template>
  <div class="home_post_list">
    <section class="home-post-section home-section">
      <div class="home-section-header">Latest-Post</div>
      <div class="post-list-wrapper">
        <PostList class="row1" rowsNumber="1" maxNumber="3"/>
        <PostList class="row2" rowsNumber="2" maxNumber="3"/>
        <PostList class="row3" rowsNumber="3" maxNumber="3"/>
      </div>
      <div class="more-posts">
        <span @click="handleRouter('all')">Read More</span>
      </div>
    </section>
    <section class="home-opensource-section home-section">
      <div class="home-section-header">Open-Source</div>
      <div class="opensource-list-wrapper">
        <article class="opensource-item-wrapper">
          <a class="opensource-item" href="https://github.com/DendiSe7enGitHub/Align">
            <div class="opensource-item-header">
              <img class="opensource-item-header-img" src="../assets/logo.svg">
            </div>
            <h3 class="opensource-name">Align</h3>
            <p class="opensource-description">Real-time, Beautiful blog generator, Auto deploy</p>
          </a>
        </article>
      </div>
    </section>
  </div>
</template>

<script>
import { postData } from "../utils/data.js";
import { getAllCategories } from "../utils/datafilter.js";
export default {
  // 主页
  name: "Home",
  data() {
    return {
      allPosts: JSON.parse(postData),
      categories: getAllCategories(JSON.parse(postData))
    };
  },
  components: {
    PostList: () => import("../components/PostList")
  },
  methods: {
    handleRouter: function(dir, categorie = "") {
      let path;
      if (categorie) {
        path = `/${dir}?${dir}=${categorie}`;
      } else {
        path = `/${dir}`;
      }
      this.$router.push(path);
    }
  }
};
</script>

<style scoped>
.container {
  max-width: 800px;
  width: 800px;
  margin: 0 auto;
  position: relative;
}
.home_post_list {
  display: flex;
  flex-direction: column;
  margin-bottom: 5rem;
}
.post-list-wrapper {
  display: flex;
}
.home-section .home-section-header {
  display: block;
  text-transform: uppercase;
  font-size: 0.55rem;
  letter-spacing: 8.6px;
  opacity: 0.7;
  padding-bottom: 1rem;
  border-bottom: 1px solid #ccc;
  margin-top: 2rem;
  text-align: left;
  padding-left: 4rem;
  cursor: pointer;
}
.opensource-list-wrapper {
  padding: 1rem;
  display: flex;
  justify-content: space-between;
}
.opensource-list-wrapper .opensource-item-wrapper {
  width: 20%;
  border: 1px solid #ccc;
  padding: 1rem;
  border-radius: calc(0.25rem - 1px);
}

.opensource-item-wrapper .opensource-item-header {
  background: #f05a5a;
}
.opensource-item-wrapper .opensource-item {
  background-image: url(https://marketplace-images.githubusercontent.com/703/8af94adc-e40e-11e7-8871-55e85b471458?auto=webp&format=jpeg&width=600);
  background-size: cover;
  background-position: center top;
  color:#585858;
}

.opensource-item-wrapper:hover {
  -webkit-animation: wobble-hor-bottom 0.8s both;
  animation: wobble-hor-bottom 0.8s both;
}
.home-section .home-section-header::first-letter {
  color: #42b983;
  font-size: 1.3rem;
}
.home-post-section .more-posts {
  font-size: 1rem;
  display: flex;
  justify-content: center;
}
.home-post-section span {
  padding: 0.5rem;
  border: 1px solid #ccc;
  border-radius: 4px;
  opacity: 0.7;
  cursor: pointer;
}
.home-post-section span:hover {
  color: #42b983;
  border-color: #ffffff;
}
@media screen and (max-width: 1000px) and (min-width: 300px) {
  .home_post_list {
    display: flex;
    flex-direction: column;
  }
}
/* ----------------------------------------------
 * Generated by Animista on 2018-12-18 6:46:16
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation wobble-hor-bottom
 * ----------------------------------------
 */
@-webkit-keyframes wobble-hor-bottom {
  0%,
  100% {
    -webkit-transform: translateX(0%);
    transform: translateX(0%);
    -webkit-transform-origin: 50% 50%;
    transform-origin: 50% 50%;
  }
  15% {
    -webkit-transform: translateX(-30px) rotate(-6deg);
    transform: translateX(-30px) rotate(-6deg);
  }
  30% {
    -webkit-transform: translateX(15px) rotate(6deg);
    transform: translateX(15px) rotate(6deg);
  }
  45% {
    -webkit-transform: translateX(-15px) rotate(-3.6deg);
    transform: translateX(-15px) rotate(-3.6deg);
  }
  60% {
    -webkit-transform: translateX(9px) rotate(2.4deg);
    transform: translateX(9px) rotate(2.4deg);
  }
  75% {
    -webkit-transform: translateX(-6px) rotate(-1.2deg);
    transform: translateX(-6px) rotate(-1.2deg);
  }
}
@keyframes wobble-hor-bottom {
  0%,
  100% {
    -webkit-transform: translateX(0%);
    transform: translateX(0%);
    -webkit-transform-origin: 50% 50%;
    transform-origin: 50% 50%;
  }
  15% {
    -webkit-transform: translateX(-30px) rotate(-6deg);
    transform: translateX(-30px) rotate(-6deg);
  }
  30% {
    -webkit-transform: translateX(15px) rotate(6deg);
    transform: translateX(15px) rotate(6deg);
  }
  45% {
    -webkit-transform: translateX(-15px) rotate(-3.6deg);
    transform: translateX(-15px) rotate(-3.6deg);
  }
  60% {
    -webkit-transform: translateX(9px) rotate(2.4deg);
    transform: translateX(9px) rotate(2.4deg);
  }
  75% {
    -webkit-transform: translateX(-6px) rotate(-1.2deg);
    transform: translateX(-6px) rotate(-1.2deg);
  }
}
</style>
